apiVersion: v1
kind: Namespace
metadata:
  name: bmasterai
---
apiVersion: v1
kind: Secret
metadata:
  name: bmasterai-secrets
  namespace: bmasterai
type: Opaque
stringData:
  anthropic-api-key: "your-anthropic-api-key-here"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmasterai-gradio
  namespace: bmasterai
  labels:
    app: bmasterai-gradio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmasterai-gradio
  template:
    metadata:
      labels:
        app: bmasterai-gradio
    spec:
      containers:
      - name: bmasterai-gradio
        image: bmasterai/gradio-app:latest
        ports:
        - containerPort: 7860
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: bmasterai-secrets
              key: anthropic-api-key
        - name: MODEL_NAME
          value: "claude-3-5-sonnet-20241022"
        - name: MAX_TOKENS
          value: "4096"
        - name: TEMPERATURE
          value: "0.7"
        - name: GRADIO_SERVER_NAME
          value: "0.0.0.0"
        - name: GRADIO_SERVER_PORT
          value: "7860"
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 7860
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bmasterai-gradio-service
  namespace: bmasterai
spec:
  selector:
    app: bmasterai-gradio
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bmasterai-gradio-ingress
  namespace: bmasterai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - bmasterai.yourdomain.com
    secretName: bmasterai-tls
  rules:
  - host: bmasterai.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bmasterai-gradio-service
            port:
              number: 80
