apiVersion: v1
kind: Secret
metadata:
  name: bmasterai-secrets
  namespace: bmasterai
  labels:
    app: bmasterai
type: Opaque
data:
  # Base64 encoded secrets - replace with your actual values
  # To encode: echo -n "your-value" | base64
  
  # OpenAI API Key (required)
  OPENAI_API_KEY: "eW91ci1vcGVuYWktYXBpLWtleQ=="  # your-openai-api-key
  
  # Anthropic API Key (optional)
  ANTHROPIC_API_KEY: "eW91ci1hbnRocm9waWMtYXBpLWtleQ=="  # your-anthropic-api-key
  
  # Slack Webhook URL (optional)
  SLACK_WEBHOOK_URL: "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20v..."  # https://hooks.slack.com/...
  
  # Email configuration (optional)
  EMAIL_USERNAME: "eW91ci1lbWFpbEBnbWFpbC5jb20="  # your-email@gmail.com
  EMAIL_PASSWORD: "eW91ci1hcHAtcGFzc3dvcmQ="  # your-app-password
  SMTP_SERVER: "c210cC5nbWFpbC5jb20="  # smtp.gmail.com
  
  # Qdrant Cloud configuration (for RAG features)
  QDRANT_URL: "aHR0cHM6Ly95b3VyLWNsdXN0ZXIucWRyYW50LmlvLw=="  # https://your-cluster.qdrant.io/
  QDRANT_API_KEY: "eW91ci1xZHJhbnQtYXBpLWtleQ=="  # your-qdrant-api-key
---
# Instructions for updating secrets:
# kubectl create secret generic bmasterai-secrets \
#   --from-literal=OPENAI_API_KEY=your-actual-key \
#   --from-literal=ANTHROPIC_API_KEY=your-actual-key \
#   --from-literal=SLACK_WEBHOOK_URL=your-actual-url \
#   --from-literal=EMAIL_USERNAME=your-email \
#   --from-literal=EMAIL_PASSWORD=your-password \
#   --from-literal=SMTP_SERVER=smtp.gmail.com \
#   --from-literal=QDRANT_URL=your-qdrant-url \
#   --from-literal=QDRANT_API_KEY=your-qdrant-key \
#   --namespace bmasterai