apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmasterai-service-account
  namespace: bmasterai
  labels:
    app: bmasterai
  annotations:
    # For AWS EKS with IAM roles for service accounts (IRSA)
    # Replace with your actual role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/bmasterai-eks-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bmasterai
  name: bmasterai-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bmasterai-role-binding
  namespace: bmasterai
subjects:
- kind: ServiceAccount
  name: bmasterai-service-account
  namespace: bmasterai
roleRef:
  kind: Role
  name: bmasterai-role
  apiGroup: rbac.authorization.k8s.io