apiVersion: v1
kind: Service
metadata:
  name: bmasterai-service
  namespace: bmasterai
  labels:
    app: bmasterai
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bmasterai
    component: agent
---
apiVersion: v1
kind: Service
metadata:
  name: bmasterai-internal
  namespace: bmasterai
  labels:
    app: bmasterai
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bmasterai
    component: agent