apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bmasterruns.bmasterai.ai
spec:
  group: bmasterai.ai
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                userId:
                  type: string
                  description: Identifier for the user who initiated the LLM run
                model:
                  type: string
                  description: The LLM model used for this run (e.g., gpt-4, claude-3-sonnet)
                namespace:
                  type: string
                  description: The namespace or environment where the run occurred (e.g., production, staging)
                inputTokens:
                  type: integer
                  description: Number of input tokens consumed by the LLM
                  minimum: 0
                outputTokens:
                  type: integer
                  description: Number of output tokens generated by the LLM
                  minimum: 0
                costUsd:
                  type: number
                  description: Cost of this LLM run in USD
                  minimum: 0
                tools:
                  type: array
                  description: List of tools used during this LLM run
                  items:
                    type: string
                maxTokens:
                  type: integer
                  description: Maximum number of tokens allowed for this run
                  minimum: 0
                temperature:
                  type: number
                  description: Temperature setting used for this LLM run
                  minimum: 0
                  maximum: 2
                topP:
                  type: number
                  description: Top-p (nucleus) sampling setting used for this LLM run
                  minimum: 0
                  maximum: 1
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: Run phase (e.g., Pending, Running, Succeeded, Failed)
                  enum:
                    - Pending
                    - Running
                    - Succeeded
                    - Failed
                traceID:
                  type: string
                  description: OpenTelemetry trace ID for this run
                errorCount:
                  type: integer
                  description: Number of errors encountered during this run
                  minimum: 0
                startTime:
                  type: string
                  format: date-time
                  description: Timestamp when the run started
                endTime:
                  type: string
                  format: date-time
                  description: Timestamp when the run ended
                processingTimeMs:
                  type: integer
                  description: Total processing time in milliseconds
                  minimum: 0
                costUsd:
                  type: number
                  description: Actual cost of this LLM run in USD (may differ from spec)
                  minimum: 0
                metadata:
                  type: object
                  description: Additional metadata about the run
                  properties:
                    toolsUsed:
                      type: array
                      items:
                        type: string
                    userId:
                      type: string
                    sessionId:
                      type: string
                    tags:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    plural: bmasterruns
    singular: bmasterrun
    kind: BMasterRun
    shortNames:
      - bmrun