apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 8192
      memory_limiter:
        check_interval: 1s
        limit_mib: 4000
        spike_limit_mib: 500
        ballast_size_mib: 500
      # Add attributes processor to enrich telemetry data
      attributes:
        actions:
          - key: service.name
            value: "bmasterai-llm-telemetry"
            action: upsert
          - key: service.namespace
            value: "observability"
            action: upsert

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "bmasterai"
        send_timestamps: true
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true
      loki:
        endpoint: "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"
        labels:
          resource:
            - service.name
            - service.namespace
      tempo:
        endpoint: "tempo.observability.svc.cluster.local:4317"
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [tempo]
        logs:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [loki]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, attributes]
          exporters: [prometheus]