{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bmasterai.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmasterai.labels" . | nindent 4 }}
    component: data
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass | default .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bmasterai.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmasterai.labels" . | nindent 4 }}
    component: logs
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  storageClassName: {{ .Values.persistence.logs.storageClass | default .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}