{{- if or .Values.secrets.openaiApiKey .Values.secrets.anthropicApiKey .Values.secrets.slackWebhookUrl .Values.secrets.emailUsername .Values.secrets.emailPassword .Values.secrets.smtpServer .Values.secrets.qdrantUrl .Values.secrets.qdrantApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmasterai.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmasterai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey }}
  {{- end }}
  {{- if .Values.secrets.slackWebhookUrl }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl }}
  {{- end }}
  {{- if .Values.secrets.emailUsername }}
  EMAIL_USERNAME: {{ .Values.secrets.emailUsername }}
  {{- end }}
  {{- if .Values.secrets.emailPassword }}
  EMAIL_PASSWORD: {{ .Values.secrets.emailPassword }}
  {{- end }}
  {{- if .Values.secrets.smtpServer }}
  SMTP_SERVER: {{ .Values.secrets.smtpServer }}
  {{- end }}
  {{- if .Values.secrets.qdrantUrl }}
  QDRANT_URL: {{ .Values.secrets.qdrantUrl }}
  {{- end }}
  {{- if .Values.secrets.qdrantApiKey }}
  QDRANT_API_KEY: {{ .Values.secrets.qdrantApiKey }}
  {{- end }}
{{- end }}