apiVersion: v1
kind: Service
metadata:
  name: {{ include "bmasterai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmasterai.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bmasterai.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bmasterai.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmasterai.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bmasterai.selectorLabels" . | nindent 4 }}